### ISSUE TITLE
Cannot find file libms5803.so.0

### ISSUE THREAD

**Issue by JackDinkel** [wrobell/libms5803#1]
I downloaded the code and installed per the instructions here: https://github.com/TomDeVlaminck/libms5803

However, when I try to run your example script, I get the following error:
Traceback (most recent call last):
  File "Pressure_Test.py", line 19, in <module>
    sensor = ms5803.Sensor("/dev/i2c-1", 0x76)
  File "/data/Git/SIMBACDH/flight/sensors/ms5803/glue.py", line 33, in **init**
    self._lib = ct.CDLL('libms5803.so.0')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: libms5803.so.0: cannot open shared object file: No such file or directory

Do you know what might cause this?

**Comment by wrobell** [comment]
Have you compiled the library?

**Comment by JackDinkel** [comment]
Maybe a stupid question, how do you compile the library?

Also, I got this warning when running "autoreconf -i":
configure.ac:10: warning: macro `AM_PATH_CHECK' not found in library
autom4te: cannot open autom4te.cache/requests: Permission denied
aclocal: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

Thanks for the help!!

**Comment by JackDinkel** [comment]
Never mind! I got it working!!

By the way, in your example script, you divide pressure by 10000, which generally causes the value to go to zero when it is floored. If you divide by 10 to get millibars however, it seems to work much better.

Thank you so much!!!!!

**Comment by wrobell** [comment]
If you are using Python 2, then the value gets floored, indeed. This is not the case in Python 3 (which I am using)
```
$ python2
Python 2.7.9 (default, Dec 11 2014, 04:42:00)  
>>> 9500 / 10000
0

$ python3
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
>>> 9500 / 10000
0.95
```
